---
title: C6312 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: mikeblome
ms.author: mblome
manager: jillfra
ms.openlocfilehash: 5011bd00f9fa61b646419b80afcd86dca686a005
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/23/2019
ms.locfileid: "68152364"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

경고 C6312: 무한 루프가:의 예외 필터 식에서 상수 exception_continue_execution을 사용 하 여-제외 하 고  
  
 이 경고는 상수를 사용 하 여 나타냅니다 `EXCEPTION_CONTINUE_EXECUTION` (또는-1로 계산 되는 다른 상수)의 구조적된 예외 처리기의 필터 식입니다. 상수 값을 사용 하 여 `EXCEPTION_CONTINUE_EXECUTION` 무한 루프가 발생할 수 있습니다. 예를 들어, 하드웨어는 예외가 발생 하는 경우 예외를 발생 시킨 명령은 다시 시작 됩니다. 예외를 발생 시킨 주소가 여전히 잘못 된 경우 다른 예외가 발생 하는 동일한 방식으로 처리 합니다. 이렇게 하면 무한 루프입니다.  
  
 에 대 한 명시적 호출 `RaiseException` 는 직접적 원인 무한 루프를 하지만 보호 된 블록에서 계속 코드를 실행 합니다. 예상 값, 수 및 경우 무한 루프가 발생할 수 있습니다이 `RaiseException` 잘못 된 포인터 역참조를 방지 하는 데 사용 되었습니다.  
  
 일반적으로 `EXCEPTION_CONTINUE_EXECUTION` 예외를 발생 시킨 포인터 또는 내부 메모리가 수정할 수 있는 필터 식에서 호출 된 함수에 의해서만 반환 해야 합니다.  
  
## <a name="example"></a>예제  
 다음 코드에서는이 경고를 생성합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 이 경고를 해결 하려면 다음 코드를 사용 합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
