---
title: C6322
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6322
helpviewer_keywords:
- C6322
ms.assetid: fb23d2b1-b2a0-465c-8bf5-ec039c6c7757
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 9e583add48ff6eb60f3d7f8baf7dc9899af94eb4
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 10/07/2019
ms.locfileid: "72011902"
---
# <a name="c6322"></a>C6322
경고 C6322: 빈 _except 블록

 이 메시지는 _except 블록에 코드가 없음을 나타냅니다. 따라서 예외가 처리 되지 않을 수 있습니다.

## <a name="example"></a>예제
 다음 코드에서는이 경고를 생성 합니다.

```
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void fd(char *pch)
{
   __try
     {
       // exception rasied if pch is null
       *pch= 0 ;
     }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION)
     {
     }
}
```

 이 경고를 해결 하려면 다음 코드를 사용 합니다.

```
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void f(char *pch)
{
   __try
     {
       // exception rasied if pch is null
      *pch= 0 ;
     }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
     {
       // code to handle exception
       puts("Exception Occurred");
     }
}
```

## <a name="see-also"></a>관련 항목
 [try-except 문](/cpp/cpp/try-except-statement)